# Generated by Django 5.2.4 on 2025-07-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_menuitem_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='named_url',
            field=models.BooleanField(default=False),
        ),
    ]
